[project]
name = "fed_debt"
version = "0.1"
dependencies = [
  "pandas>=2.1.1",
  "click>=8.1.7",
  "mypy>=1.5.1",
]

[tool.mypy]
strict = true
install_types = "True"
non_interactive = "True"
exclude = ["build", "docs"]
disallow_untyped_decorators = "False"
